import gzip
import json
from spacious_corpus.lang_id import LanguageIdentifier
import langcodes


def filter_item(item, lang):
    score = item['score']
    text = item['text']
    subreddit = item['subreddit']
    
    # Posts in English require a score of 4 or more to be part of the corpus.
    # In other languages, we require a score of 2 or more.
    if lang != 'en':
        score += 2
    return (
        len(item['text']) >= 40
        and score >= 4
        and 'jerk' not in subreddit
        and 'okbuddy' not in subreddit
        and 'gonewild' not in subreddit
        # the next lines match several COVID-denial subreddits that were banned
        # in September 2021
        and 'newnormal' not in subreddit
        and 'new_normal' not in subreddit
        and not item.get('quarantined')
        and 'i am a bot' not in text.casefold()
        and "i'm a bot" not in text.casefold()
    )


def run():
    lid = LanguageIdentifier()
    for line in gzip.open('data/tmp/reddit-2019-06-50.gz', 'rt', encoding='utf-8'):
        item = json.loads(line)
        if not item.get('quarantined') and 'body' in item:
            text = item['body']
            subreddit = item['subreddit']
            plausible_languages = ['en'] + SUBREDDIT_LANGUAGES.get(subreddit, [])
            lang, confidence = lid.detect_language(text)
            lang_match, _ = langcodes.closest_match(lang, plausible_languages)
            if lang_match != 'und' and confidence > .8 and filter_item(item, lang_match):
                textform = text.replace('\n', ' ')
                score = item['score']
                print(f'{lang_match}\t{score}\t{subreddit}\t{textform}')


SUBREDDIT_LANGUAGES = {
    '600euro': ['de'],
    'aarhus': ['da'],
    'aeiou': ['de'],
    'agraelus': ['cs'],
    'afdwatch': ['de'],
    'aktiemarknaden': ['sv'],
    'albania': ['sq'],
    'allsvenskan': ['sv'],
    'alt_fakten': ['de'],
    'altgreece': ['el'],
    'ametistru': ['ru'],
    'amizadevirtual': ['pt'],
    'amsterdam': ['nl'],
    'ani_bm': ['he'],
    'animeitaly': ['it'],
    'anormaldayinrussia': ['ru'],
    'arabs': ['ar'],
    'argaming': ['es'],
    'argentina': ['es'],
    'argentinabenderstyle': ['es'],
    'argentos': ['es'],
    'armemeia': ['hy'],
    'armenia': ['hy'],
    'arkisuomi': ['fi'],
    'asklatinamerica': ['es'],
    'askspain': ['es'],
    'asiatripper': ['zh-Hans'],
    'austria': ['de'],
    'automobil': ['de'],
    'bakanewsjp': ['ja'],
    'bakchodi': ['hi'],
    'bancadelmeme': ['it'],
    'barclona': ['es'],
    'baris_irl': ['tr'],
    'baxov': ['cs'],
    'belgica': ['nl'],
    'belgium': ['nl'],
    'belohorizonte': ['pt'],
    'benfica': ['pt'],
    'berlin': ['de'],
    'biblioteca': ['pt'],
    'bgy': ['tr'],
    'bocajuniors': ['es'],
    'brasil': ['pt'],
    'brasil_drama': ['pt'],
    'brasilcentro': ['pt'],
    'brasildob': ['pt'],
    'brasilivre': ['pt'],
    'brasilnoticias': ['pt'],
    'brasilonreddit': ['pt'],
    'buecher': ['de'],
    'bundeswehr': ['de'],
    'bulgaria': ['bg'],
    'bundesliga': ['de'],
    'burdurland': ['tr'],
    'cabocajuniors': ['es'],
    'canada': ['fr'],
    'canadaguns': ['fr'],
    'canadapoliticshumor': ['fr'],
    'canadients': ['fr'],
    'cariverplate': ['es'],
    'casualph': ['tl'],
    'catalunya': ['ca'],
    'cellbits': ['pt'],
    'chernobyl': ['uk'],
    'chile': ['es'],
    'china_irl': ['zh-Hans'],
    'chonglangtv': ['zh'],
    'colombia': ['es'],
    'conseiljuridique': ['fr'],
    'croatia': ['hr'],
    'czech': ['cs'],
    'dachschaden': ['de'],
    'danishents': ['da'],
    'dankgentina': ['es'],
    'dankmark': ['da'],
    'de': ['de'],
    'de_edv': ['de'],
    'de_iama': ['de'],
    'demorda': ['uk'],
    'denmark': ['da'],
    'derechogenial': ['es'],
    'derwachsen': ['de'],
    'desabafos': ['pt'],
    'dkfinance': ['da'],
    'dndnl': ['nl'],
    'duklock': ['cs', 'sk'],
    'dutchfire': ['nl'],
    'dsa_rpg': ['de'],
    'ecuador': ['es'],
    'ecuadornoticias': ['es'],
    'eesti': ['et'],
    'egypt': ['ar'],
    'einfach_posten': ['de'],
    'eredivisie': ['nl'],
    'everlastingsummerru': ['ru'],
    'es': ['es'],
    'espanol': ['es'],
    'esperanto': ['eo'],
    'europe': ['de', 'es', 'fr', 'it', 'nl', 'ru', 'sv', 'uk'],
    'exlldm': ['es'],
    'fabricadenoobs': ['pt'],
    'fahrrad': ['de'],
    'fashionrepspolska': ['pl'],
    'feminisme': ['fr'],
    'fenerbahcesk': ['tr'],
    'fewjar': ['de'],
    'fcporto': ['pt'],
    'filme': ['de'],
    'filosofia': ['pt'],
    'financaspessoaispt': ['pt'],
    'finanzen': ['de'],
    'flamengo': ['pt'],
    'forum_democratie': ['nl'],
    'fosttalicska': ['hu'],
    'fragreddit': ['de'],
    'france': ['fr'],
    'francelibre': ['fr'],
    'francophonie': ['fr'],
    'freedutch': ['nl'],
    'french': ['fr'],
    'frenchhelp': ['fr'],
    'fulbo': ['es'],
    'futebol': ['pt'],
    'g0ularte': ['pt'],
    'gamemeneersubmissies': ['nl'],
    'gamesecultura': ['pt'],
    'geldzaken': ['nl'],
    'german': ['de'],
    'germantrees': ['de'],
    'germany': ['de'],
    'germanrap': ['de'],
    'gothenburg': ['sv'],
    'greece': ['el'],
    'guatemala': ['es'],
    'hamburg': ['de'],
    'hanguk': ['ko'],
    'hanzememes': ['nl'],
    'helsinki': ['fi'],
    'hungarian': ['hu'],
    'hungary': ['hu'],
    'iceland': ['is'],
    'ich_iel': ['de'],
    'ik_ihe': ['nl'],
    'iksdagen': ['sv'],
    'indianonpolitical': ['hi'],
    'indonesia': ['id'],
    'investimentos': ['pt'],
    'israel': ['he'],
    'italia': ['it'],
    'italian': ['it'],
    'italy': ['it'],
    'italyinformatica': ['it'],
    'italymotori': ['it'],
    'ithadtobebrazil': ['pt'],
    'jesubrodre': ['da'],
    'jeremyfrieser': ['nl'],
    'jeuxvideo': ['fr'],
    'jisakupc': ['ja'],
    'jogatina': ['pt'],
    'justvidman': ['hu'],
    'kerala': ['ml'],
    'kgbtr': ['tr'],
    'klengan': ['de'],
    'kopyamakarna': ['tr'],
    'kosovo': ['sq'],
    'labelleprovince': ['fr'],
    'laesterschwestern': ['de'],
    'lal_salaam': ['ml'],
    'latinopeopletwitter': ['es'],
    'latvia': ['lv'],
    'learnspanish': ['es'],
    'learnjapanese': ['ja'],
    'lekkerspelen': ['nl'],
    'liberta': ['ru'],
    'ligue1': ['fr'],
    'lisboa': ['pt'],
    'lithuania': ['lt'],
    'litigi': ['it'],
    'livros': ['pt'],
    'ltb_iel': ['de'],
    'maau': ['es'],
    'madrid': ['es'],
    'malaysia': ['ms'],
    'memederwoche': ['de'],
    'memexico': ['es'],
    'mercadoreddit': ['es'],
    'merval': ['es'],
    'metaquebec': ['fr'],
    'mexico': ['es'],
    'militaresenreddit': ['es'],
    'mitosyleyendasonline': ['es'],
    'mkd': ['mk'],
    'moldova': ['ro'],
    'monterrey': ['es'],
    'montreal': ['fr'],
    'montrealimpact': ['fr'],
    'motorsports_ja': ['ja'],
    'mujico': ['es'],
    'nederlands': ['nl'],
    'newsbahia': ['pt'],
    'newsdk': ['da'],
    'newsnepal': ['ne'],
    'newsg': ['ja'],
    'newsokunomoral': ['ja'],
    'newsokur': ['ja'],
    'nhaa': ['pt'],
    'ni_bondha': ['te'],
    'nicaragua': ['es'],
    'noboctb': ['ru'],
    'norge': ['no'],
    'norskfotball': ['no'],
    'notargentina': ['es'],
    'oknotizie': ['it'],
    'panama': ['es'],
    'paraguay': ['es'],
    'paris': ['fr'],
    'patopapao': ['pt'],
    'perguntereddit': ['pt'],
    'personalfinancecanada': ['fr'],
    'peru': ['es'],
    'pescocofino': ['pt'],
    'philippines': ['tl', 'ceb'],
    'phr4r': ['tl'],
    'pietsmiet': ['de'],
    'pikabu': ['hy', 'ru'],
    'pikabuoc': ['ru'],
    'pikabupolitics': ['ru'],
    'podemos': ['es'],
    'poldersocialisme': ['nl'],
    'poland': ['pl'],
    'polska': ['pl'],
    'popular_science_ru': ['pt'],
    'portugal': ['pt'],
    'portugalcaralho': ['pt'],
    'portugallafora': ['pt'],
    'portugalnews': ['pt'],
    'portuguese': ['pt'],
    'prague': ['cs'],
    'primeiraliga': ['pt'],
    'projetohumanos': ['pt'],
    'puertorico': ['es'],
    'quebec': ['fr'],
    'rance': ['fr'],
    'rbtv_cj': ['de'],
    'redditvn': ['vi'],
    'republicaargentina': ['es'],
    'republica_argentina': ['es'],
    'robac': ['ro'],
    'rocketbeans': ['de'],
    'roma': ['it'],
    'romania': ['ro'],
    'romemes': ['ro'],
    'rothwellden': ['cs'],
    'rotterdam': ['nl'],
    'rpg_brasil': ['pt'],
    'ru': ['ru'],
    'ru_anime': ['ru'],
    'rupolitika': ['ru'],
    'russia': ['ru'],
    'russian': ['ru'],
    'sakartvelo': ['ka'],
    'santiago': ['es'],
    'saopaulo': ['pt'],
    'saopaulofc': ['pt'],
    'saraba1st': ['zh-Hans'],
    'saraba2nd': ['zh-Hans'],
    'saudiarabia': ['ar'],
    'scandinavia': ['da', 'no', 'sv'],
    'serbia': ['sr'],
    'slovakia': ['sk'],
    'slovenia': ['sl'],
    'soccer': ['de', 'es', 'fi', 'fr', 'he', 'it', 'nl', 'no', 'pt', 'tr'],
    'spain': ['es'],
    'spanish': ['es'],
    'sportingcp': ['pt'],
    'sprechstunde': ['de'],
    'sqdc': ['fr'],
    'stanga': ['ro'],
    'stockholm': ['sv'],
    'suomi': ['fi'],
    'superlig': ['tr'],
    'svenska': ['sv'],
    'sverige': ['sv'],
    'sveriges_politik': ['sv'],
    'svenskpolitik': ['sv'],
    'svihs': ['tr'],
    'swarje': ['sv'],
    'sweddituniversalis': ['sv'],
    'sweden': ['sv'],
    'swedents': ['sv'],
    'swedishproblems': ['sv'],
    'tamamahbapengelli': ['tr'],
    'tecnologia': ['es'],
    'thaithai': ['th'],
    'thepanturkism': ['tr'],
    'tijuana': ['es'],
    'tiodopave': ['pt'],
    'thenetherlands': ['nl'],
    'toronto': ['fr'],
    'turkey': ['tr'],
    'turkeylgbt': ['tr'],
    'turkeymiddleeast': ['ar'],
    'uacommunity': ['ru', 'uk'],
    'unket': ['sv'],
    'ukraina': ['ru', 'uk'],
    'uruguay': ['es'],
    'vegande': ['de'],
    'venezuela': ['es'],
    'vfbstuttgart': ['de'],
    'vosfinances': ['fr'],
    'vrouwvolk': ['nl'],
    'vzla': ['es'],
    'wallonia': ['fr'],
    'wasletztepreis': ['de'],
    'weibsvolk': ['de'],
    'wien': ['de'],
    'wortwitzkasse': ['de'],
    'yapanfasha': ['he'],
    'yointerneto': ['es'],
    'youtubememesfr': ['fr'],
}


run()